using System.IO;
using System.Linq;
using GameCode.Spirits.Data;
using UnityEditor;
using UnityEngine;

namespace GameCode.Spirits.Editor.Tools
{
    public static class SpiritDocsGenerator
    {
        [MenuItem("Spirits/Generate Documentation", priority = 60)]
        public static void GenerateDocs()
        {
            string outDir = "Assets/Documentation/Spirits";
            if (!Directory.Exists(outDir))
            {
                Directory.CreateDirectory(outDir);
            }

            GenerateTopicsDoc(outDir);
            GenerateEventsDoc(outDir);
            GenerateArchitectureDiagram(outDir);

            AssetDatabase.Refresh();
            Debug.Log($"[SpiritDocs] Documentation generated at {outDir}");
        }

        private static void GenerateTopicsDoc(string outDir)
        {
            var guids = AssetDatabase.FindAssets("t:TopicDefinition");
            var topics = guids.Select(g => AssetDatabase.LoadAssetAtPath<TopicDefinition>(AssetDatabase.GUIDToAssetPath(g)))
                              .OrderBy(t => t.Category)
                              .ThenBy(t => t.DisplayName)
                              .ToList();

            using (StreamWriter writer = new StreamWriter($"{outDir}/Topics.md"))
            {
                writer.WriteLine("# Spirit Topics Registry");
                writer.WriteLine("This document is auto-generated by the Spirit System Editor Tooling.");
                writer.WriteLine();

                string currentCategory = "";
                foreach (var topic in topics)
                {
                    if (topic.Category != currentCategory)
                    {
                        currentCategory = topic.Category;
                        writer.WriteLine($"## {currentCategory}");
                    }

                    writer.WriteLine($"### {topic.DisplayName} (`{topic.Id.Value}`)");
                    writer.WriteLine(topic.Description);
                    writer.WriteLine();
                }
            }
        }

        private static void GenerateEventsDoc(string outDir)
        {
            var guids = AssetDatabase.FindAssets("t:GameplayEventDefinition");
            var events = guids.Select(g => AssetDatabase.LoadAssetAtPath<GameplayEventDefinition>(AssetDatabase.GUIDToAssetPath(g)))
                              .OrderBy(e => e.Category)
                              .ThenBy(e => e.DisplayName)
                              .ToList();

            using (StreamWriter writer = new StreamWriter($"{outDir}/Events.md"))
            {
                writer.WriteLine("# Spirit Events Registry");
                writer.WriteLine("This document is auto-generated by the Spirit System Editor Tooling.");
                writer.WriteLine();

                foreach (var e in events)
                {
                    writer.WriteLine($"### {e.DisplayName} (`{e.Id.Value}`)");
                    writer.WriteLine($"**Category:** {e.Category}");
                    writer.WriteLine(e.Description);
                    writer.WriteLine();
                }
            }
        }

        private static void GenerateArchitectureDiagram(string outDir)
        {
            using (StreamWriter writer = new StreamWriter($"{outDir}/Architecture.md"))
            {
                writer.WriteLine("# Spirit System Architecture");
                writer.WriteLine("Auto-generated diagram.");
                writer.WriteLine();
                writer.WriteLine("```mermaid");
                writer.WriteLine("graph TD;");
                
                var spiritGuids = AssetDatabase.FindAssets("t:SpiritDefinition");
                var spirits = spiritGuids.Select(g => AssetDatabase.LoadAssetAtPath<SpiritDefinition>(AssetDatabase.GUIDToAssetPath(g))).ToList();
                
                foreach (var spirit in spirits)
                {
                    writer.WriteLine($"    Spirit_{spirit.Id.Value}[{spirit.DisplayName}] --> Comm_{spirit.Id.Value}(Communication);");
                    writer.WriteLine($"    Spirit_{spirit.Id.Value} --> Id_{spirit.Id.Value}(Identity);");
                }

                writer.WriteLine("```");
            }
        }
    }
}
