using GameCode.Spirits.Core;
using GameCode.Spirits.Runtime;

namespace GameCode.Spirits.Communication
{
    /// <summary>
    /// Represents a fully resolved and localized line of dialogue ready for coordination.
    /// This is generated by the Dialogue Resolution Layer by translating a CommunicationIntent.
    /// </summary>
    public struct DialogueRequest
    {
        /// <summary>
        /// The Spirit who will speak this line.
        /// </summary>
        public readonly Spirit SourceSpirit;

        /// <summary>
        /// The fully resolved localized text to be displayed or spoken.
        /// </summary>
        public readonly string LocalizedText;

        /// <summary>
        /// The urgency of the dialogue. Used by the Coordinator for sorting/interrupting.
        /// </summary>
        public readonly PriorityTier Priority;

        /// <summary>
        /// The precise length of time this dialogue should be displayed/played.
        /// Resolved by the IDialogueResolver (e.g. from authored data or length calculation).
        /// </summary>
        public readonly float Duration;

        /// <summary>
        /// Optional contextual data passed down from the intent (e.g., specific target listener).
        /// </summary>
        public readonly object Context;

        public DialogueRequest(Spirit sourceSpirit, string localizedText, PriorityTier priority, float duration, object context = null)
        {
            SourceSpirit = sourceSpirit;
            LocalizedText = localizedText;
            Priority = priority;
            Duration = duration;
            Context = context;
        }
    }
}
