using GameCode.Spirits.Core;
using GameCode.Spirits.Runtime;

namespace GameCode.Spirits.Communication
{
    /// <summary>
    /// Represents a fully resolved and localized line of dialogue ready for coordination.
    /// This is generated by the Dialogue Resolution Layer by translating a CommunicationIntent.
    /// </summary>
    public struct DialogueRequest
    {
        /// <summary>
        /// The Spirit who will speak this line.
        /// </summary>
        public readonly Spirit SourceSpirit;

        /// <summary>
        /// The localization key or direct text (depending on the game's localization setup) 
        /// to be displayed or spoken.
        /// </summary>
        public readonly string TextKey;

        /// <summary>
        /// The urgency of the dialogue. Used by the Coordinator for sorting/interrupting.
        /// </summary>
        public readonly PriorityTier Priority;

        /// <summary>
        /// Optional contextual data passed down from the intent (e.g., specific target listener).
        /// </summary>
        public readonly object Context;

        public DialogueRequest(Spirit sourceSpirit, string textKey, PriorityTier priority, object context = null)
        {
            SourceSpirit = sourceSpirit;
            TextKey = textKey;
            Priority = priority;
            Context = context;
        }
    }
}
