namespace GameCode.Spirits.Agency
{
    /// <summary>
    /// The actionable output generated by the Agency system when a Concern crosses 
    /// a critical threshold. This struct describes internal motivation (what the Spirit 
    /// is worried about and how strongly) rather than dictating external behavior.
    /// In Phase 3, Communication systems will consume this to determine dialogue priorities.
    /// </summary>
    public struct AgencyImpulse
    {
        /// <summary>
        /// The specific internal concern that generated this impulse.
        /// </summary>
        public readonly Concern DrivingConcern;

        /// <summary>
        /// The raw strength of the impulse at the moment it was generated.
        /// </summary>
        public readonly float Intensity;

        /// <summary>
        /// Creates a new impulse driven by a specific concern.
        /// </summary>
        public AgencyImpulse(Concern drivingConcern, float intensity)
        {
            DrivingConcern = drivingConcern;
            Intensity = intensity;
        }
    }
}
